config/routes.rb
Rails.application.routes.draw do
  get "/", to: "members#index"
  resources :members
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  validates :name, :phone, :email, presence: true
  validates_uniqueness_of :name, :email
  validates :phone, :format => /\A\d{2}\-\d{8}\z/
  validates :email, :format => /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :find_member, only: [:edit, :update, :destroy]
  def index
    @members = Member.order(id: :asc)
  end

  def new
    @member = Member.new
  end

  def create
    # if Member.where(name != :name)
    @member = Member.new(member_params)
    # end
    if @member.save
      redirect_to members_path, notice: "new member created success."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @member.update(member_params)
      redirect_to  members_path, notice: 'member profile updated!'
    else
      render :edit
    end
  end

  def destroy
    @member.destroy if @member
    redirect_to members_path, notice: 'member profile deteled!'
  end

  private
  def member_params
    params.require(:member).permit(:name, :phone, :email)
  end

  def find_member
    @member = Member.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Rakuten</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'true' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'true' %>

  <%#= javascript_pack_tag 'hello_vue' %>
  <%#= stylesheet_pack_tag 'hello_vue' %>

  <%= javascript_pack_tag 'main' %>
  <%= stylesheet_pack_tag 'main' %>

</head>

<body>
  <div class="container" id="app">
    <%= yield %>
  </div>
  <script src="//unpkg.com/babel-polyfill@latest/dist/polyfill.min.js"></script>
  <script src="//unpkg.com/tether@latest/dist/js/tether.min.js"></script>
  <script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.js"></script>
</body>

</html>

app/views/members/_form.html.erb
<%= simple_form_for(member) do |m| %>
<%= m.input :name, label: "Name" %>
<%= m.input :phone, label: "Phone" %>
<%= m.input :email, label: "E-mail" %>
<%= m.submit :class => 'btn btn-outline-primary', :style => 'display: inline-block' %>
<%= link_to 'Back to Members List', members_path, :class => 'btn btn-outline-secondary', :style => 'display: inline-block' %>
<% end %>

app/views/members/edit.html.erb
<h1>Edit Member</h1>

<%= render 'form', member: @member %>

app/views/members/index.html.erb
<h1>Members List</h1>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <td>No.</td>
      <td>Name</td>
      <td>Phone</td>
      <td>E-mail</td>
      <td>Edit</td>
      <td>Delete</td>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
    <tr>
      <td><%= member.id %></td>
      <td><%= member.name %></td>
      <td><%= member.phone %></td>
      <td><%= member.email %></td>
      <td>
        <%= link_to 'Edit', edit_member_path(member), :class => 'btn btn-outline-secondary' %>
      </td>
      <td>
        <%= link_to 'Delete', member_path(member), method: 'delete', data: {confirm: "Are you sure you want to delete?" }, :class => 'btn btn-outline-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New Member", new_member_path, :class => 'btn btn-outline-primary' %>
<br>
<br>
<app-2></app-2>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>